# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

users = User.create(
  [{id: 1, email: Faker::Internet.email, name: 'Author 1'},
  {id: 2, email: Faker::Internet.email, name: 'Author 2'},
  {id: 3, email: Faker::Internet.email, name: 'Contributer 1'},
  {id: 4, email: Faker::Internet.email, name: 'Contributer 2'}]
)

contributers = Contributer.create(
  [{id: 1, user_id: 3},
  {id: 2, user_id: 4},
  {id: 3, user_id: 1}]
)

stories = Story.create(
  [{id: 1, creator_id: 1, title: "The Cottage in the Woods"},
  {id: 2, creator_id: 1, title: 'The pen is mightier than the sword'},
  {id: 3, creator_id: 2, title: 'To A Plot'},
  {id: 4, creator_id: 2, title: 'The Stream'}]
)

story_components = StoryComponent.create(
  [{id: 1, story_id: 1, contributer_id: 3, component_type: 'intro', body: "A perfunctory look as one was passing this quirky little stone cottage might draw only superficial assumptions: a tale of a once immaculately kept garden; vibrant, twinkling stained glass windows. But the privet boundary has become unruly from neglect and intermittent rain has left muddy tears on the windows, draining the colour from them. Monstrous trees cast dark, shapeless shadows across the tired brick path that meanders its way onwards to meet the natural beauty of stained wood. The years have been peeled away to reveal the door’s former glory, vein-like grain running through unyielding English oak.
    \n At the foot of the door lies a mat with the sole word ‘Welcome’ dyed, cerise pink, in its prickles. A, rather conspicuous, white plastic intercom has been fitted next to the original brass doorbell. Shadow and light have broken through the dulled green leaves and red rose petals within the bevelled glass, creating warm spots on the slightly scuffed floorboards through the hallway. They creak a little in certain places. About half way up the right-hand wall are three surprisingly loud bursts of oil on canvass – none of which make any logical sense to the fingertips."},
  {id: 2, story_id: 1, contributer_id: 1, component_type: 'conflict', body: "Smooth, young walls in neutral shades of fresh cream and mocha have been left as matt foundation. Wooden slatted blinds hang, slightly crooked, at small windows through which warm sunbeams gently flow, magnified, bouncing back off the tempered glass of a coffee table. A vase of deep lavender Angel Face roses sit, about centre, amid an assortment of literature and audio CDs. The intense aroma rising like plumes weaves its way into every nook of the space. 
    \n Two sofas, perpendicular to each other, frame the coffee table. The thick beige cotton is punctuated by cushions of various sizes and shapes in hues of duck-egg blue – some, with a satin-like smoothness, some, soft and furry and some, a bumpy, dense cotton weave. Forty-five degrees to the left stands a single armchair which has been recovered in dark chocolate corduroy. Several short, blonde hairs have stuck, stubbornly, to the navy blue velvet cushion propped upon it, despite attempts to remove every last one; a folded fleece blanket has successfully prevented others from naughtily breaching authorised boundaries."},
  {id: 3, story_id: 1, contributer_id: 2, component_type: 'resolution', body: "Six steps to the right and warm, stubbly sea grass meets the cool, hard tile of the open plan dining kitchen. Behind the subtle pink, black and grey mottled marble breakfast bar several labelled jars stand on counters although, at first glance, they may appear quite blank. The jars are arranged left to right, tallest to shortest. Cupboards house neatly grouped cans with raised markings on them: tinned fruit on the left, tinned vegetables on the right, packets in the centre and so on. The hob has a protective glass cover and notches have been etched into the dials. A small cubic bookcase stands against the adjoining wall to the living room. It has been placed on its side so only reaches hip height. It contains an eclectic buffet of recipe books – some large, heavy hardbacks, some small paperbacks, encased in plastic covers, each with a sticker along the spine and front cover. On the floor, touching the right side base of the bookcase is a large metal bowl of water that makes a rather unpleasant scraping noise when nudged. A small puddle has accumulated around the perimeter and erratically dispersed blobs of saliva mixed with fresh water create a slimy trail in the direction of the armchair, and the still warm blanket."},
  
  {id: 4, story_id: 2, contributer_id: 2, component_type: 'intro', body: "Stveerlowahd was crossing the icy tundra, her sleigh drawn by two powerful elks, the arctic wind thrashing their shaggy coats. She had to reach the Cavern of Our Lord of Creation and convince Him to transform the genetic inheritence of Man before it was too late. War was about to break out yet again – but this time, although destruction would not be complete, the long term effects of their biological and nuclear weapons on all living creatures would mean the end of any life form as we now know it. All new life would be born with mutations with few possibilities for survival. 
    \n Stveerlowahd was nearing her destination. The midnight sun glimmered on the horizon as the petrifying wind calmed. The huge entrance to the Cavern was visible at the base of a solitary scrag which jutted up from the frozen land. As the sensation of calm and relief began to fill her heart she became aware of a low humming sound and her eyes began to pick out dark flowing shapes approaching at speed from the horizon. She insinctively urged on her sleigh bearers, as yet unaware as to who or what these figures might be. Their supernatural speed meant that instants later their origin was but too clear. Confusion and fear paralysed her movements. The War Lords – come to defend their rights to perpetual battles. Had she come this far only to be defeated at the very Gates of Peace? Her beasts hurtled onwards despite their mistress’ uncertainty. The sky blackened as the deathly forms swarmed towards her. Stveerlowahd gripped the Shield of Peace and raised it heavenwards against their onslaught."},
  {id: 5, story_id: 2, contributer_id: 2, component_type: 'conflict', body: "‘In the name of Our Lord of Peace – Return to Hell!’ 
    \n With a strepitus roar the sky cracked open. Mighty beams shooting from above formed a luminous dome around Stveerlowahd, allowing her sleigh to advance towards the entrance. All the while the forces of Evil continued crashing and ricocheting against its impenetratable barrier. The War Lords could not allow any change in Man’s genetic make up – this chromosomatic weakness which allowed Evil to multiply and Its power to intensify. But the power of the Sheild of Peace was greater than the power of the War Lords and Stveerlowahd passed unharmed into the Cavern. 
    \n ‘Your mission?’ boomed the voice of The Creator"},
  {id: 6, story_id: 2, contributer_id: 1, component_type: 'resolution', body: "‘My Lord’, Stveerlowahd kneeled, bowing low. ‘Man is endangering the survival of all living creatures on our planet. His genetic programming means our world can never be free from wars – and today's knowledge has allowed the creation of weapons of greater destruction than ever before. The forces of Evil have become stronger than the forces of Peace. Only My Lord can save life by removing this weak chromosome.’ 
    \n ‘Stveerlowahd, your mission is a noble one but when Man was formed I permitted the existence of a gene which urged men to fight – to enable them to struggle for survival in a hostile environment. That men allow this strength to be taken advantage of by the Forces of Evil is for them to overcome. Fortunately, when creating Woman, the bearer of new life, I also created a gene to defend life and it is for women to use their power to overcome the Evil forces which have corrupted men. You, Stveerlowahd, leader of women, must continue your battle – harness the Forces of Peace and you will overcome the Forces of Evil’"},
  
  {id: 7, story_id: 3, contributer_id: 2, component_type: 'intro', body: "I wake, full of excitement like a child on Christmas morning and listen carefully. Outside the birds are singing and I hear an early morning train pulling out of the nearby station; but I don’t hear rain. Perfect. Within the hour we’re ready to go, the battered old flask is full of hot, strong tea and bread and cheese are stuffed into a bag. My husband, Alex, chucks boots and spades in the car and we’re off. After a year-long wait we’ve got an allotment. 
    \n Leaving our small town behind, the scenery changes to gently rolling countryside, fields of sheep and new-born lambs surround us, nodding daffodils by the roadside look like little yellow flags telling us spring is here. Away in the distance I see the smudgy blues and purples of the Ochil hills. Soon we’re standing on our 10 x 10 metre plot grinning at each other and itching to get started."},
  {id: 8, story_id: 3, contributer_id: 1, component_type: 'conflict', body: "We start to dig, the spade I’m using belonged to my late mum and for a split second, as I take hold of the smooth, wooden handle, it feels almost like our hands have touched again. I quickly get into a rhythm, thudding the blade into the earth, stepping hard on it and heaving the load up. Before long I’m huffing and puffing and glad of the cool breeze on my face, and I start to tune in to other sounds around me-Alex, breathing hard but still grinning, saying, “Great way to spend my birthday”, the hungry-sounding bleat of a lamb calling to its mother, a tractor’s engine chugging as it ploughs the neighbouring field and the noisy seagulls following it. Far above us larks sing. Then suddenly, as if someone has flicked a switch, the sun bursts through the cloud turning the tractor a brighter red, the earth at my feet a richer brown and even the worms a deeper pink. My mind empties and I feel as free as the larks. "},
  {id: 9, story_id: 3, contributer_id: 2, component_type: 'resolution', body: "Two solid hours of digging later, we’re more than ready for a break and sink down heavily on a knee-high pile of turf, gulp the hot tea and tuck into our bread and cheese. Somehow this closeness to nature and working the land gives me a comforting feeling of timelessness and I think of Robert Burns, that great Scottish poet, writing “To a Mouse ( on Turning her up in her Nest with the Plough)” centuries before. 
    \n But there’s work to be done. Another couple of hours of back-breaking digging and we decide to call it a day, I ache pretty much all over by now and have to drag myself to the car. We stop at a pub called the Four Marys and stepping inside, our eyes slowly adjusting to the dark interior, it feels warm and inviting with a fire crackling in the hearth. We order beer and find a seat by the fire-the place is full, there’s a hubbub of voices and outbursts of laughter. Stretching out our aching legs we feel tired but contented and raise our glasses, “Happy birthday!” I say. And we drink to life."},
  
  {id: 10, story_id: 4, contributer_id: 2, component_type: 'intro', body: "I stared out over the hillside. I could just see the sea out of the corner of the window but the mainly I could see the Mackenzie’s untidy, ramshackle house and the cars, vans and tractors that seemed to be in permanent disrepair. I thought of how my father had loved this place and the childhood holidays I had spent with my brothers, playing on the darkening hillside. My parents had never grasped that this far north, dark descended slowly and so much later. They would feed us Hobnobs and slices of bread with Dairylea through the kitchen window until late in the evening, whenever we came gambolling up, hungry again. 
    \n I had always loved the cottage. It represented a freedom that I never felt in London. I felt at ease and as if I had morphed from the me that was always on the outside of things into the real me. My brothers and I would make up adventures. For six weeks every summer we became the “fearless three”. We would build camps in the ruins of the old village, collect the skulls of sheep that had died on the hillside, invent stories, adventures and rituals, build dams across the small rivulets. We didn’t need other children to play with. For some reason the three of us became a harmonious whole on the island. 
    \n We were only segmented in the early mornings, when we would each, in turn, have an adventure with my father. I loved it when it was my turn. I felt so special. I was always ready and had sneaked downstairs to wait for my father to get up. We had prepared everything the night before. I didn’t really care about the rods and the little bag of floats and reels and of course the box of maggots. I just wanted to go on our expedition."},
  {id: 11, story_id: 4, contributer_id: 3, component_type: 'conflict', body: "I brought myself back to the present. Why not? I thought. It wasn’t far. It had been years since I had gone to “the Stream”. It had been out of bounds to us unless we were with my father. I pulled on my climbing boots and left the cottage climbing the slope opposite. 
    \n The Stream wasn’t far, but I had to cross the hillside first. At the top of the slopes I smelt the May flowers of the white hawthorn. I just stood and looked down to the Kilbrennan Sound, breathing in the sweet smell and watching the few sail boats in the sea below.
    \n I could no longer see the metal carcasses that until just minutes before had invaded the view. I turned to walk across the rough ground towards the Stream. The peaty earth gave a bounce to my step as I walked through the heather. Every so often there were patches of yellow celandine and scatterings of speedwell as well as some other tiny flowers that I couldn’t identify. I wished I could. My father had known all the wild flowers. We had collected them when we were little and brought them back to the house to identify from all of the books that we had. How I missed his quiet serenity. He loved the holidays that we spent together and collecting the flowers, the seaweeds, the bugs and beasties from rock-pools that we would take proudly back to my mother to look up."},
  {id: 12, story_id: 4, contributer_id: 3, component_type: 'resolution', body: "I shook myself and walked on. The bracken was getting thicker now, though I could still wade through it easily, not like it would be in a few months. The path no longer existed. As the old crofter villages in the hills had declined and the modern villages around the coast road had sprung up, so the tracks had grown over, but I pushed on. I was sure I would find the way through again. 
    \nI could smell the dampness of the woods ahead of me, the peaty smell wafting up with each step. In the distance I heard a lamb bleating for its negligent mother who had wandered off. The sound always made me anxious.
    \nI found an old sheep track, heading through the bracken and the young birch trees and followed it deeper into the woodland. I could hear the Stream now and followed the sound of it, louder and louder. When I was younger and with my father we would be off to catch trout for my mother’s breakfast. He would only ever take one of us at a time because the slopes down to the Stream were so steep. He would sit me down on the fallen trunk of an old oak tree and take my little rod and tackle bag from me. He would slither and stumble through the dewy grass and moss down to the ledge and then come back for me, then we would do the same journey together. He always told me to hold onto the bracken as I went sliding down.
    \nThe Stream frightened me. There was so much noise as the water crashed into the pool that we would fish in. But I also felt so secure at the same time. I was with my father, nothing bad could happen. I always pretended that I liked the fishing because I was afraid that he would stop taking me if he realised that I didn’t like putting the maggots onto the hook. My hands always shook as I did it though I could weight the lines and attach the floats easily. Once our lines in the pool we would break open the paper bag with our “piece”, take out the packet of Hobnobs and just sit and wait. 
    \nI found the old fence and followed it up to the gate. It was broken and I couldn’t open it. I had to squeeze through to follow the sheep track on the other side down towards the water. Bluebells covered the mossy floor of the wood and I could hear birds around me though I couldn’t spot any of them. I could see the edge of the hillside and knew the Stream was at the bottom. I zigzagged my way down the slippery slope. I had seen the place we used to fish, recognising it from the old bridge, broken even when I was I child. Two of the four logs were dangling into the water. Years ago it was the crossing from the old village to the farm on the other side.
    \nThe sides of the Stream were steep and wet with the spray from the waterfall. I remembered how I had always thought of this as a fairy dell. It was the only thing that I didn’t share with my brothers. It was too “girly” for them. Now I looked through my adult eyes and thought exactly with same. The pool was deep and the waterfall steep. Splinters of sunlight fell through the branches of the trees, sparkling on the tumbling water. The walls of the pool were lined with moss and fronds of bracken. I could see some wild primroses on the other side. The wood of oak, rowan and birch trees was so peaceful. I just sat. I closed my eyes and lay down against the moss-covered tree trunk behind me. I listened. The gentle rustle of the wind in the young trees and the bracken around me, the water as it pounded the pool below, the invisible birds above me. 
    \nI don’t know how long I stayed there. I roused feeling cold but that was more because of the dampness seaping through my clothes than any chill in the air. I raised myself and feeling a peace that I had not felt since my father’s funeral set off up the slope again, hauling myself up the steep hill using the young bracken shoots as I had done as a child. Coming out of the woodland, I again breathed in the sweetness of the ancient hawthorn and looking from the swathes of wild violets up into the mountains, I saw a pair of buzzard, circling in on the wind."}]
)